config/routes.rb
Rails.application.routes.draw do
  get 'reportes/index'

  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado', as: :listado

  get 'personas/:id/:inst/:muni/:f1/:f2/reporte_municipio' => 'personas#reporte_municipio', as: :reporte_municipio
  get 'personas/:id/reporte_municipio_listado' => 'personas#reporte_municipio_listado', as: :reporte_municipio_listado
  get 'personas/:id/:fecha1/:fecha2/reporte_ayuda' => 'personas#reporte_ayuda', as: :reporte_ayuda
  get 'personas/:fecha1/:fecha2/reporte_totales_sectores' => 'personas#reporte_totales_sectores', as: :reporte_totales_sectores
  get 'personas/:id/:fecha/reporte_por_institucion' => 'personas#reporte_por_institucion', as: :reporte_por_institucion
  get 'personas/:id/:muni/:f1/:f2/:sector/:ayuda/reporte_listado_rango' => 'personas#reporte_listado_rango', as: :reporte_listado_rango

  root 'personas#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/institution.rb
class Institution < ActiveRecord::Base
   has_one :ayuda
   validates :nombre , uniqueness: true
   validates :nombre,  :presence =>true

   def self.search(search)
     where("nombre LIKE ? ", "%#{search}%" )
   end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  def index
    @institutions = Institution.all.order("orden ASC").page(params[:page]).per(20)
      if params[:search]
        @institutions = Institution.search(params[:search]).order("orden ASC").page(params[:page]).per(20)
      else
        @institutions = Institution.all.order('orden ASC').page(params[:page]).per(20)
      end
  end

  def show
  end

  def new
    @institution = Institution.new
  end

  def edit
  end

  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'La institución ha sido almacenada exitosamente.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'La institución ha sido actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'La institución ha sido eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_institution
      @institution = Institution.find(params[:id])
    end

    def institution_params
      params.require(:institution).permit(:nombre,:orden)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= simple_form_for @institution, :html=> { class: 'form-horizontal' }  do |f| %>
<% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "Error") %>  Durante la Inserción de la Institución. Revisar:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Nombre: </label>
                    <br />
                    <label for="">Orden: </label>

                </div>
                <div class="form-input col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                               <%= f.input :nombre, label: false , :placeholder=>"Nombre de la Institución"%> 
                               <br />
                               <%= f.input :orden, label: false , :placeholder=>"Orden" %>
                        </div>

                    </div>
                </div>



            </div>



  <div class="btn primary-bg medium">
    <%= f.button :submit  %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
                <div id="page-title">

<h3>
    Editar Institución
    <small>
         Se editan los datos de las Instituciones
    </small>
</h3>
                   
</div><!-- #page-title -->

<%= render 'form' %>
<br/>
<%= link_to 'Mostrar', @institution %> |
<%= link_to 'Volver', institutions_path %>
					

app/views/institutions/index.html.erb
<div id="page-title">

<h3>
    Listado de Instituciones
    <small>
        Listado de instituciones que brindan ayuda en la jornada <b>Corazon Adentro</b>
    </small>
</h3>

</div><!-- #page-title -->
<div class="form-row">
        <div class="form-label col-md-3">
            <label for="">Agregue un criterio de busqueda
        </div>
        <div class="form-input col-md-9">
            <div class="row">
                <div class="col-md-3">
                <%= form_tag(institutions_path, :method => "get", id: "search-form", :html=> { class: 'form-horizontal' })do %>
                <%= text_field_tag :search, params[:search], placeholder: "Buscar Institución" %>
                    <%= submit_tag "Buscar" %>
                <% end %>
                </div>
            </div>
        </div>
    </div>


<p id="notice"><%= notice %></p>




<%= link_to  new_institution_path,:class=> "btn medium bg-blue" do %>
                                      <span class="button-content text-transform-upr font-bold font-size-11">Nueva institucion</span>
<% end -%>


<div class="divider"></div>


<% if @institutions.present? %>
<div class="example-box">
<table class="table table-hover">

  <thead>
    <tr>
      <th>#ID</th>
      <th>Nombre</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.id %></td>
        <td><%= institution.nombre %></td>
  <td>
                <%= link_to  institution  do %>
                 <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>

                 <%= link_to edit_institution_path(institution) do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>

                 <%= link_to  institution, method: :delete, data: { confirm: 'Are you sure?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                    <% end -%>
  </td>


      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
       <th>#ID</th>
      <th>Nombre</th>
      <th>Opciones</th>
    </tr>
  </tfoot>
</table>
<br/>
<% else %>
  <p> no hay instituciones(s) con este criterio de busqueda: <%= params[:search] %>.</p>

<% end -%>
<br>

<%= paginate @institutions %>


</div>

app/views/institutions/new.html.erb
                <div id="page-title">

<h3>
    Nueva Institución
    <small>
         se agregan los datos de las Instituciones
    </small>
</h3>
                   
</div><!-- #page-title -->
<%= render 'form' %>
<br/>
<%= link_to 'Volver', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>
<br/>

<h4 class="heading-1 clearfix">
    <i class="glyph-icon icon-tags heading-icon"></i>
    <div class="heading-content">
       <%=  'Datos de la Institución'%>.
        <small>
			 <p>
			  <strong>Nombre:</strong>
			  <%= @institution.nombre %>
			</p>
        </small>
    </div>
</h4>


<%= link_to 'Editar', edit_institution_path(@institution) %> |
<%= link_to 'Volver', institutions_path %>