config/routes.rb
Rails.application.routes.draw do
  get 'reportes/index'

  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado', as: :listado

  get 'personas/:id/:inst/:muni/:f1/:f2/reporte_municipio' => 'personas#reporte_municipio', as: :reporte_municipio
  get 'personas/:id/reporte_municipio_listado' => 'personas#reporte_municipio_listado', as: :reporte_municipio_listado
  get 'personas/:id/:fecha1/:fecha2/reporte_ayuda' => 'personas#reporte_ayuda', as: :reporte_ayuda
  get 'personas/:fecha1/:fecha2/reporte_totales_sectores' => 'personas#reporte_totales_sectores', as: :reporte_totales_sectores
  get 'personas/:id/:fecha/reporte_por_institucion' => 'personas#reporte_por_institucion', as: :reporte_por_institucion
  get 'personas/:id/:muni/:f1/:f2/:sector/:ayuda/reporte_listado_rango' => 'personas#reporte_listado_rango', as: :reporte_listado_rango

  root 'personas#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/locality.rb
class Locality < ActiveRecord::Base
   validates :municipio, :sector, :fecha,  :presence =>true
   validates :municipio, uniqueness: {scope: [:municipio, :sector, :fecha], allow_blank: false, :message => "Error el registro ya existe"}


   def self.search(search)
     where("municipio LIKE ? or sector LIKE ? or fecha LIKE ?", "%#{search}%", "#{search}", "%#{search}%")
   end

end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  def index
    @localities = Locality.all.order("fecha DESC").page(params[:page]).per(20)
      if params[:search]
        @localities = Locality.search(params[:search]).order("fecha DESC").page(params[:page]).per(20)
      else
        @localities = Locality.all.order('fecha DESC').page(params[:page]).per(20)
      end
  end

  def show
  end

  def new
    @locality = Locality.new
  end

  def edit
  end

  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'La localidad ha sido almacenada exitosamente.' }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: 'La localidad ha sido actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: 'La localidad ha sido eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:municipio, :sector, :fecha, :activo)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= simple_form_for @locality, :html=> { class: 'form-horizontal' }  do |f| %>
 <% if @locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locality.errors.count, "error") %>  Durante la Inserción de la Localidad. Revisar:</h2>
        <ul>
      <% @locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Municipio: </label>
                </div>
                <div class="form-input col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                               <%= f.input :municipio, label: false, collection: ['Maneiro','Arismendi', 'Garcia', 'Mariño'],  prompt: 'Seleccione el municipio' %>
                        </div>

                    </div>
                </div>
            </div>



            <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Sector: </label>
                </div>
                <div class="form-input col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                              <%= f.input :sector,  label: false, :placeholder=>'Sector' %>
                        </div>


                    </div>
                </div>
            </div>
               <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Fecha:</label>
                </div>
                <div class="form-input col-md-4">
                    <div class="row">
                        <div class="col-md-4">
                              <%= f.input :fecha, label: false %>
                        </div>


                    </div>
                </div>
            </div>

              <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Estado:</label>
                </div>
                <div class="form-input col-md-4">
                    <div class="row">
                        <div class="col-md-4">
                                <%= f.input :activo, label: 'Activo' %>
                        </div>


                    </div>
                </div>
            </div>

  <div class="btn primary-bg medium">
    <%= f.button :submit  %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<div id="page-title">

<h3>
    Editar Localidad
    <small>
         Se editan los datos de las Localidades a Visitar
    </small>
</h3>
        
</div><!-- #page-title -->

<%= render 'form' %>
<br/>
<%= link_to 'Mostrar', @locality %> |
<%= link_to 'Volver', localities_path %>

app/views/localities/index.html.erb
<div id="page-title">

<h3>
    Listado de Localidades
    <small>
        Listado de localidades en la jornada  <b>Corazon Adentro</b>
    </small>
</h3>

</div><!-- #page-title -->




<p id="notice"><%= notice %></p>
<div class="form-row">
        <div class="form-label col-md-3">
            <label for="">Agregue un criterio de busqueda
        </div>
        <div class="form-input col-md-9">
            <div class="row">
                <div class="col-md-3">
                <%= form_tag(localities_path, :method => "get", id: "search-form", :html=> { class: 'form-horizontal' })do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Buscar Localidad" %>
                    <%= submit_tag "Buscar" %>
                <% end %>
                </div>
            </div>
        </div>
    </div>


<%= link_to  new_locality_path,:class=> "btn medium bg-blue" do %>
                                      <span class="button-content text-transform-upr font-bold font-size-11">Nueva Localidad </span>
<% end -%>

<div class="divider"></div>
<% if @localities.present? %>
<div class="example-box">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Fecha</th>
      <th>Municipio</th>
      <th>Sector</th>
      <th>Activo</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @localities.each do |locality| %>
      <tr class="odd gradeX">
              <td>
                <%= locality.id%>
              </td>
        <td><%= locality.fecha.strftime("%d/%m/%Y") %></td>

        <td><%= locality.municipio %></td>
        <td><%= locality.sector %></td>
        <td><%= locality.activo %></td>

        <td >
                <%= link_to locality do %>
                 <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>

                 <%= link_to edit_locality_path(locality) do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>

                 <%= link_to  locality, method: :delete, data: { confirm: 'Estas seguro de eliminar la localidad?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                    <% end -%>

</td>

     </tr>    <% end %>



  </tbody>
</table>

<% else %>
  <p> no hay localidad(es) con este criterio de busqueda: <%= params[:search] %>.</p>

<% end -%>
<br>

<%= paginate @localities %>


</div>

app/views/localities/new.html.erb
<div id="page-title">

<h3>
    Nueva Localidad
    <small>
         Se agregan los datos de las Localidades a Visitar
    </small>
</h3>
                   
</div><!-- #page-title -->


<%= render 'form' %>
<br/>
<%= link_to 'Volver', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<h4 class="heading-1 clearfix">
    <i class="glyph-icon icon-tags heading-icon"></i>
    <div class="heading-content">
       <%=  'Datos de la Localidad'%>.
        <small>
			       <p>
			  <strong>Municipio:</strong>
			  <%= @locality.municipio %>
			</p>

			<p>
			  <strong>Sector:</strong>
			  <%= @locality.sector %>
			</p>

			<p>
			  <strong>Fecha:</strong>
			  <%= @locality.fecha %>
			</p>

			<p>
			  <strong>Activo:</strong>
			  <%= @locality.activo %>
			</p>




        </small>
    </div>
</h4>


<%= link_to 'Editar', edit_locality_path(@locality) %> |
<%= link_to 'Volver', localities_path %>