config/routes.rb
Rails.application.routes.draw do
  get 'reportes/index'

  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado', as: :listado

  get 'personas/:id/:inst/:muni/:f1/:f2/reporte_municipio' => 'personas#reporte_municipio', as: :reporte_municipio
  get 'personas/:id/reporte_municipio_listado' => 'personas#reporte_municipio_listado', as: :reporte_municipio_listado
  get 'personas/:id/:fecha1/:fecha2/reporte_ayuda' => 'personas#reporte_ayuda', as: :reporte_ayuda
  get 'personas/:fecha1/:fecha2/reporte_totales_sectores' => 'personas#reporte_totales_sectores', as: :reporte_totales_sectores
  get 'personas/:id/:fecha/reporte_por_institucion' => 'personas#reporte_por_institucion', as: :reporte_por_institucion
  get 'personas/:id/:muni/:f1/:f2/:sector/:ayuda/reporte_listado_rango' => 'personas#reporte_listado_rango', as: :reporte_listado_rango

  root 'personas#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ayuda.rb
class Ayuda < ActiveRecord::Base
 belongs_to :institution

 validates :nombre , uniqueness: true
 validates :nombre, :institution_id, :presence =>true


 def self.search(search)
   where("nombre LIKE ? ", "%#{search}%" )
 end

end

app/controllers/ayudas_controller.rb
class AyudasController < ApplicationController
  before_action :set_ayuda, only: [:show, :edit, :update, :destroy]

  # GET /ayudas
  # GET /ayudas.json

      def index
        @ayudas = Ayuda.all.order("nombre ASC").page(params[:page]).per(20)
          if params[:search]
            @ayudas = Ayuda.search(params[:search]).order("nombre ASC").page(params[:page]).per(20)
          else
            @ayudas = Ayuda.all.order('nombre ASC').page(params[:page]).per(20)
          end


      end
  # GET /ayudas/1
  # GET /ayudas/1.json
  def show
  end

  # GET /ayudas/new
  def new
    @ayuda = Ayuda.new
  end

  # GET /ayudas/1/edit
  def edit
  end

  # POST /ayudas
  # POST /ayudas.json
  def create
    @ayuda = Ayuda.new(ayuda_params)

    respond_to do |format|
      if @ayuda.save
        format.html { redirect_to @ayuda, notice: 'La Ayuda ha sido almacenda exitosamente.' }
        format.json { render :show, status: :created, location: @ayuda }
      else
        format.html { render :new }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudas/1
  # PATCH/PUT /ayudas/1.json
  def update
    respond_to do |format|
      if @ayuda.update(ayuda_params)
        format.html { redirect_to @ayuda, notice: 'La Ayuda ha sido actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @ayuda }
      else
        format.html { render :edit }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudas/1
  # DELETE /ayudas/1.json
  def destroy
    @ayuda.destroy
    respond_to do |format|
      format.html { redirect_to ayudas_url, notice: 'La Ayuda ha sido eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayuda
      @ayuda = Ayuda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayuda_params
      params.require(:ayuda).permit(:nombre, :institution_id)
    end


end

app/helpers/ayudas_helper.rb
module AyudasHelper
end

app/views/ayudas/_form.html.erb
<%= simple_form_for @ayuda, :html=> { class: 'form-horizontal' }  do |f| %>

 <% if @ayuda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ayuda.errors.count, "error") %>  Durante la Inserción de la Ayuda. Revisar:</h2>

      <ul>
      <% @ayuda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Nombre: </label>
                </div>
                <div class="form-input col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                                  <%= f.input :nombre, label: false, :placeholder=> 'Nombre de la Institución' %>
                        </div>

                    </div>
                </div>
            </div>

 <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Institución: </label>
                </div>
                <div class="form-input col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                                <%= f.association :institution, :label_method => :nombre, :value_method => :id, label: false,  prompt: 'Seleccione la Institución'%>
                        </div>

                    </div>
                </div>
            </div>

 
  <div class="btn primary-bg medium">
    <%= f.button :submit  %>
  </div>

<% end %>

app/views/ayudas/edit.html.erb
                <div id="page-title">

<h3>
   Editar Ayuda
    <small>
         Se editan los datos de las Ayudas
    </small>
</h3>
                   
</div><!-- #page-title -->

<%= render 'form' %>
<br/>
<%= link_to 'Mostrar', @ayuda %> |
<%= link_to 'Volver', ayudas_path %>

app/views/ayudas/index.html.erb
<div id="page-title">

<h3>
    Listado de Ayudas
    <small>
        Listado de ayudas disponibles en la jornada  <b>Corazon Adentro</b>
    </small>
</h3>

</div><!-- #page-title -->





<p id="notice"><%= notice %></p>
<div class="form-row">
        <div class="form-label col-md-3">
            <label for="">Agregue un criterio de busqueda
        </div>
        <div class="form-input col-md-9">
            <div class="row">
                <div class="col-md-3">
                <%= form_tag(ayudas_path, :method => "get", id: "search-form", :html=> { class: 'form-horizontal' })do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Buscar Ayuda" %>
                    <%= submit_tag "Buscar" %>
                <% end %>
                </div>
            </div>
        </div>
    </div>



<%= link_to  new_ayuda_path,:class=> "btn medium bg-blue" do %>
                                      <span class="button-content text-transform-upr font-bold font-size-11">Nueva Ayuda</span>
<% end -%>

<div class="divider"></div>

<% if @ayudas.present? %>
<div class="example-box">
<table class="table table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Nombre</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @ayudas.each do |ayuda| %>
      <tr>
	<td><%= ayuda.id %></td>
        <td><%= ayuda.nombre %></td>
	<td>
      <%= link_to  ayuda  do %>
       <i class="glyph-icon icon-download mrg5R"></i> Mostrar
      <% end -%>

       <%= link_to edit_ayuda_path(ayuda) do%>
         <i class="glyph-icon icon-edit mrg5R"></i> Editar
       <% end -%>

       <%= link_to  ayuda, method: :delete, data: { confirm: 'Are you sure?' } do%>
          <i class="glyph-icon icon-remove mrg5R"></i>Borrar
          <% end -%>
	</td>


      </tr>
    <% end %>
  </tbody>
	<tfoot>
		<tr>
			<th>ID</th>
			<th>Ayuda</th>
		  <th>Opciones</th>
		</tr>
	</tfoot>

</table>
<% else %>
  <p> no hay ayudas(s) con este criterio de busqueda: <%= params[:search] %>.</p>

<% end -%>
<br>

<%= paginate @ayudas %>


</div>
<%= link_to 'New Ayuda', new_ayuda_path %>

app/views/ayudas/new.html.erb
                <div id="page-title">

<h3>
    Nueva Ayuda
    <small>
         Se agregan los datos de las Ayudas
    </small>
</h3>
                   
</div><!-- #page-title -->

<%= render 'form' %>
<br/>
<%= link_to 'Volver', ayudas_path %>

app/views/ayudas/show.html.erb
<p id="notice"><%= notice %></p>
<br/>

<h4 class="heading-1 clearfix">
    <i class="glyph-icon icon-tags heading-icon"></i>
    <div class="heading-content">
       <%=  'Datos de la Ayuda'%>.
        <small>
			<p>
			  <strong>Nombre:</strong>
			  <%= @ayuda.nombre %>
			</p>
        </small>
    </div>
</h4>


<%= link_to 'Editar', edit_ayuda_path(@ayuda) %> |
<%= link_to 'Volver', ayudas_path %>