config/routes.rb
Rails.application.routes.draw do
  get 'reportes/index'

  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado', as: :listado

  get 'personas/:id/:inst/:muni/:f1/:f2/reporte_municipio' => 'personas#reporte_municipio', as: :reporte_municipio
  get 'personas/:id/reporte_municipio_listado' => 'personas#reporte_municipio_listado', as: :reporte_municipio_listado
  get 'personas/:id/:fecha1/:fecha2/reporte_ayuda' => 'personas#reporte_ayuda', as: :reporte_ayuda
  get 'personas/:fecha1/:fecha2/reporte_totales_sectores' => 'personas#reporte_totales_sectores', as: :reporte_totales_sectores
  get 'personas/:id/:fecha/reporte_por_institucion' => 'personas#reporte_por_institucion', as: :reporte_por_institucion
  get 'personas/:id/:muni/:f1/:f2/:sector/:ayuda/reporte_listado_rango' => 'personas#reporte_listado_rango', as: :reporte_listado_rango

  root 'personas#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :economy, dependent: :destroy
	has_many :conclusions, dependent: :destroy
	has_many :families, dependent: :destroy
	belongs_to :locality
	accepts_nested_attributes_for :economy
  accepts_nested_attributes_for :conclusions, reject_if: :all_blank ,	 :allow_destroy => true
  accepts_nested_attributes_for :families , reject_if: :all_blank , :allow_destroy => true
	validates :cedula , uniqueness: true
	validates :nombre1, :apellido1, :sexo, :direccion,:cedula, :presence=>true
	validates_presence_of :locality_id, :message=> "Debe seleccionar la fecha, el municipio y el sector"



def self.cedula(id)
	where(:id=>id)
end

def self.search(search)
  where("nombre1 LIKE ? or apellido1 LIKE ? or cedula LIKE ? or (concat(nombre1,' ',apellido1) LIKE ?)", "%#{search}%", "#{search}", "%#{search}%","%#{search}%" )
end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  layout "limpio", only: [:reporte_ayuda,:reporte_municipio,:reporte_municipio_listado,:reporte_totales_sectores,:reporte_por_institucion,  :reporte_listado_rango]

 def reporte_totales_sectores
   #hay que revisar esto bien
   @id_localidad= Locality.find_by_sql("select localities.fecha, localities.id, localities.municipio, localities.sector from localities where (fecha between '#{params[:fecha1]}' and '#{params[:fecha2]}') and localities.activo=true order by localities.fecha")
   @ayudas =Ayuda.joins(:institution).order("institutions.orden,ayudas.nombre")
   @texto="Reporte General de las Localidades desde  #{params[:fecha1]} hasta #{params[:fecha2]}"
  end


def reporte_por_institucion
    if params[:fecha]=="todos"
      @texto = "Reporte general por Institucion"
      a="select personas.id, institutions.nombre as institution, cedula,concat(nombre1,' ',apellido1) as nombres ,telefono1, direccion,conclusions.estado,localities.municipio,localities.sector,ayudas.nombre as ayuditas from personas,localities,conclusions,ayudas,institutions where personas.id=conclusions.persona_id and localities.id=conclusions.locality_id and conclusions.ayuda_id=ayudas.id and ayudas.institution_id=institutions.id and institutions.id=#{params[:id]} order by cedula "
    else
      @localidad = Locality.where(:id=> params[:fecha])
      @texto = "Reporte por Institucion en #{@localidad.last.municipio} #{@localidad.last.sector} #{@localidad.last.fecha.strftime('%d/%m/%Y')}"
      a="select personas.id, institutions.nombre as institution, cedula,concat(nombre1,' ',apellido1) as nombres ,telefono1, direccion,conclusions.estado,localities.municipio,localities.sector,ayudas.nombre as ayuditas from personas,localities,conclusions,ayudas,institutions where localities.id=#{params[:fecha]} and personas.id=conclusions.persona_id and localities.id=conclusions.locality_id and conclusions.ayuda_id=ayudas.id and ayudas.institution_id=institutions.id and  institutions.id=#{params[:id]} order by cedula "
    end

    @normal = Persona.find_by_sql("select ayudas.id,count(*) as cuenta ,localities.municipio,localities.sector ,localities.fecha, conclusions.estado, ayudas.nombre, institutions.nombre  as institucion_nombre from personas,ayudas, localities ,conclusions ,institutions where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and locality_id=#{params[:fecha]} and ayudas.institution_id = institutions.id and conclusions.estado = 'Normal' group by (conclusions.ayuda_id)")
    @urgente = Persona.find_by_sql("select ayudas.id,count(*) as cuenta , localities.municipio,localities.sector ,localities.fecha,conclusions.estado, ayudas.nombre, institutions.nombre  as institucion_nombre from personas,ayudas, localities ,conclusions ,institutions where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and locality_id=#{params[:fecha]} and ayudas.institution_id = institutions.id and conclusions.estado = 'Urgente' group by (conclusions.ayuda_id)")
    @resultado= Persona.find_by_sql("select ayudas.id,count(*) as cuenta, localities.municipio,localities.sector ,localities.fecha,ayudas.nombre, institutions.nombre  as institucion_nombre from personas,ayudas, localities ,conclusions ,institutions  where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and locality_id=#{params[:fecha]} 	  and ayudas.institution_id = institutions.id and (conclusions.estado = 'Normal' or conclusions.estado = 'Urgente' ) and institutions.id=#{params[:id]} group by (conclusions.ayuda_id) order by institutions.orden ASC")

    @institucion  = Persona.find_by_sql(a)
    @listado_ayudas = Persona.find_by_sql("select conclusions.persona_id, ayudas.nombre, conclusions.estado  from personas,ayudas, localities ,conclusions where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and ayudas.institution_id=#{params[:id]} and (conclusions.estado = 'Urgente' or conclusions.estado='Normal') order by (conclusions.ayuda_id)")
end

def reporte_listado_rango
  mun=["Antolín del Campo","Arismendi","Díaz","García","Gómez","Maneiro","Marcano", "Mariño", "Península de Macanao", "Tubores", "Villalba"]

    if params[:id]=="todos" #id de la institucion
      @texto = "Reporte General"
      i=''
      @ins=false
    else
      @ins=true
      @texto = "Reporte por Institucion "
      i="institutions.id='#{params[:id]}' and"
    end

    if params[:muni]=="todos" #municipio
      @ban=true
    else
      @ban=false
      n=params[:muni]
      m=mun[n.to_i]
      @texto = @texto+" del Municipio:  #{m}"
      a="localities.municipio='#{m}' and"
    end

    if params[:sector]=="todos" #sector
      s=''
      @ban2=true
    else
      @ban2=false
      sector = Locality.where(:id=> params[:sector])
      if !sector.blank?
        sec=sector.last.sector
        @texto = @texto+", Sector:  #{sec}"
      else
        @texto = @texto+", NO EXISTE EL SECTOR"
      end
      s="localities.sector='#{sec}' and"
    end
    if params[:ayuda]=="todos" #ayuda
      ay=''
    else
      ayu = Ayuda.where(:id=> params[:ayuda])
      if !ayu.blank?
        @texto = @texto+", Tipo de Ayuda: #{ayu.last.nombre} "
      else
        @texto = @texto+", ERROR NO EXISTE LA AYUDA"
      end
      ay="conclusions.ayuda_id='#{params[:ayuda]}' and"
    end
    if ((params[:f1]=='0' or params[:f2]=='0') or (params[:f1]=='0' and params[:f2]=='0')) #rango de fechas
      b=''
      @ban1=true
    else
      if params[:f1]==params[:f2] #rango de fechas
        @ban1=false
      else
        @ban1=true
      end
      @texto = @texto+", desde el  #{params[:f1]} hasta #{params[:f2]} "
      b="(localities.fecha between '#{params[:f1]}' and '#{params[:f2]}') and"
    end

    #and (conclusions.estado = 'Urgente' or conclusions.estado='Normal')

  @institucion  = Persona.find_by_sql("select distinct personas.id,localities.fecha,  institutions.nombre as institution, cedula,concat(nombre1,' ',apellido1) as nombres ,telefono1, direccion,conclusions.estado,localities.municipio,localities.sector,ayudas.nombre as ayuditas from personas,localities,conclusions,ayudas,institutions where #{a} #{b} #{i} #{s} #{ay} personas.id=conclusions.persona_id and localities.id=conclusions.locality_id and conclusions.ayuda_id=ayudas.id and ayudas.institution_id=institutions.id  group by cedula order by localities.fecha,cedula ASC ")
  @listado_ayudas = Persona.find_by_sql("select personas.id, institutions.nombre as institution, cedula,concat(nombre1,' ',apellido1) as nombres ,telefono1, direccion,conclusions.estado,localities.municipio,localities.sector,ayudas.nombre as ayuditas from personas,localities,conclusions,ayudas,institutions where #{a} #{b} #{i} #{s} #{ay} personas.id=conclusions.persona_id and localities.id=conclusions.locality_id and conclusions.ayuda_id=ayudas.id and ayudas.institution_id=institutions.id order by localities.fecha,cedula ASC ")

end

def reporte_ayuda

  @texto=""
  if ((params[:fecha1]=='0' or params[:fecha2]=='0') or (params[:fecha1]=='0' and params[:fecha2]=='0')) #rango de fechas
    rango=''
  else
    if params[:fecha1]==params[:fecha2] #rango de fechas
      @texto = @texto+", de la fecha: #{params[:fecha1]}  "
    else
      @texto = @texto+", desde el  #{params[:fecha1]} hasta #{params[:fecha2]} "
    end
    rango="(localities.fecha between '#{params[:fecha1]}' and '#{params[:fecha2]}') and  "
  end

  @localidad= Locality.find_by_sql("select localities.fecha, localities.id, localities.municipio, localities.sector from localities where #{rango} localities.activo=true order by localities.fecha")
end

def reporte_municipio_listado

  @listado = Persona.find_by_sql("select distinct personas.id, cedula, concat(nombre1,' ',nombre2,' ',apellido1,' ',apellido2)as nombres,concat (direccion) as direccion, telefono1,ayudas.nombre, conclusions.estado,localities.fecha,localities.municipio,localities.sector  from personas,ayudas, localities ,conclusions ,institutions where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and locality_id=#{params[:id]} and ayudas.institution_id = institutions.id and (conclusions.estado = 'Urgente' or conclusions.estado='Normal') group by (personas.cedula)")
  @listado_ayudas = Persona.find_by_sql("select conclusions.persona_id, ayudas.nombre, conclusions.estado  from personas,ayudas, localities ,conclusions where personas.id=conclusions.persona_id and conclusions.locality_id = localities.id and ayudas.id = conclusions.ayuda_id and locality_id=#{params[:id]} and (conclusions.estado = 'Urgente' or conclusions.estado='Normal') order by (conclusions.ayuda_id)")

end


def reporte_municipio
  mun=["Antolín del Campo","Arismendi","Díaz","García","Gómez","Maneiro","Marcano", "Mariño", "Península de Macanao", "Tubores", "Villalba"]

      @texto=""
      if params[:id]=="todos" #id de la localidad
        loca=''
      else
        localidad = Locality.where(:id=> params[:id])
        if !localidad.blank?
          @texto = @texto+" Municipio:  #{localidad.last.municipio} - Sector: #{localidad.last.sector} - Fecha: #{localidad.last.fecha}"
        else
          @texto = @texto+", ERROR NO EXISTE LA LOCALIDAD"
        end
        loca="conclusions.locality_id='#{params[:id]}' and"
      end

      if params[:inst]=="todos" #id de la institucion
        ins=''
      else
        institucion = Institution.where(:id=> params[:inst])
        if !institucion.blank?
          @texto=@texto+" - Institución: #{institucion.last.nombre}"
        else
          @texto = @texto+", ERROR NO EXISTE LA INSTITUCION"
        end
        ins="institutions.id='#{params[:inst]}' and"

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_conclusion_fields.html.erb
<div class="nested-fields">
        <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Conclusion de la ayuda </label>
                </div>

                <div class="form-input col-md-10">
                    <div class="row">
                        <div class="col-md-4">
                          <%= f.input :ayuda_id , collection: Ayuda.all.order('nombre ASC').pluck("nombre", "id"), as: :select,  prompt: '*Seleccione la solicitud'  %>

                        </div>
                        <div class="col-md-3">
                          *Estado de solicitud <%= f.input :estado, collection: ['Normal', 'No Procede', 'Urgente'], label: false,  prompt: '*Seleccione el Estado'%>
                        </div>
                        <div class="col-md-4">
                          *Localidad (Fecha, Municipio, Sector)<%= f.select :locality_id, Locality.where(:activo=>true).order('fecha DESC').map { |r| [r.fecha.strftime("%d/%m/%Y").to_s+" "+r.municipio+" - "+r.sector, r.id] }, include_blank: false,  prompt: 'Seleccione ',label: false,  prompt: '*Seleccione localidad' %>

                        </div>


                      <!--div class="col-md-3">
                          Fecha de solicitud <%#= f.input :fecha ,as: :date,start_year: Date.today.year - 0,
                              end_year: Date.today.year - 0, discard_day: false,
                              order: [:day,:month, :year] , label: false%>
                                <%= f.input :fecha,  as: :date, html5: true%>
                        </div>-->


                    </div>
                </div>

      <div class="col-md-6">
        <%= link_to_remove_association  f,  :class=> "btn medium bg-red" do%>
          <span class="button-content text-transform-upr font-bold font-size-11">Remover Ayuda</span>
        <%end %>
      </div>



 </div>
</div>

app/views/personas/_family_fields.html.erb
<div class="nested-fields">
        <div class="form-row">
                <div class="form-label col-md-2">
                    <label for="">Familiares </label>
                </div>
                <div class="form-input col-md-10">
                    <div class="row">
                      <div class="col-md-2">
                        <%= f.input :cedula, label: "Cedula", :placeholder=>"Cedula de Identidad"%>
                       <%#= f.input :parentesco, collection: ['Padre','Madre', 'Abuelo(a)', 'Tio(a)','Primo(a)', 'Hijo(a)','Sobrino(a)','Nieto(a)','Esposo(a)', 'Yerno(a)', 'Suegro(a)', 'Cuñado(a)'], label: "Parentesco",  prompt: 'Seleccione el parentesco'%>
                      </div>
                        <div class="col-md-2">
                          <%= f.input :nombre , :placeholder=>'*Nombre' %>

                        </div>
                        <div class="col-md-2">
                         <%= f.input :apellido , :placeholder=>'*Apellido'%>
                        </div>
                        <div class="col-md-3">
                            <div class="bfh-datepicker">

                           <%= f.input :fecha_nac,  as: :date, html5: true, label: 'Fecha de Nacimiento'%>
                          </div>

                        </div>

                        <div class="col-md-3">

                         <%= f.input :parentesco, collection: ['Padre','Madre', 'Hermano(a)','Abuelo(a)', 'Tio(a)','Primo(a)', 'Hijo(a)','Sobrino(a)','Nieto(a)','Esposo(a)', 'Yerno(a)', 'Suegro(a)', 'Cuñado(a)','Concubino(a)'], label: "Parentesco",  prompt: 'Seleccione el parentesco'%>
                        </div>




                    </div>
                </div>

      <div class="col-md-6">
        <%= link_to_remove_association  f,  :class=> "btn medium bg-red" do%>
          <span class="button-content text-transform-upr font-bold font-size-11">Remover Familiar</span>
        <%end %>

      </div>
 </div>
</div>

app/views/personas/edit.html.erb
                <div id="page-title">

<h3>
    Editar Persona
    <small>
         se editan los datos de las personas y solicitudes
    </small>
</h3>
                 
</div><!-- #page-title -->
<%= render 'form' %>
<br/>
<%= link_to 'Mostrar', @persona %> |
<%= link_to 'Volver', personas_path %>

app/views/personas/index.html.erb
<div id="page-title">

<h3>
    Listado de Personas
    <small>
        Listado de personas solicitando ayudas en la jornada  <b>Corazon Adentro</b>
    </small>
</h3>

</div><!-- #page-title -->


<p id="notice"><%= notice %></p>



        <div class="form-row">
                <div class="form-label col-md-3">
                    <label for="">Agregue un criterio de busqueda
                </div>
                <div class="form-input col-md-9">
                    <div class="row">
                        <div class="col-md-3">
                        <%= form_tag(personas_path, :method => "get", id: "search-form", :html=> { class: 'form-horizontal' })do %>
                            <%= text_field_tag :search, params[:search], placeholder: "Buscar Solicitud" %>
                            <%= submit_tag "Buscar" %>
                        <% end %>
                        </div>
                    </div>
                </div>
            </div>




<%= link_to  new_persona_path,:class=> "btn medium bg-blue" do %>
                                      <span class="button-content text-transform-upr font-bold font-size-11">Nueva Persona</span>
<% end -%>

<div class="divider"></div>

<h3>

</h3>
<p class="font-gray-dark">


</p>



<script type="text/javascript">

$(document).ready(function() {

});

</script>


<% if @personas.present? %>
<div class="example-box">
<table class="table table-hover" >
<thead>
		<tr>
			<th>#</th>
			<th>Nombres y Apellidos</th>
			<th>Cedula</th>
			<th>Telefono</th>
			<th>Opciones</th>

		</tr>
	</thead>
	<tbody>
 <% @personas.each do |persona| %>
      <tr>
      	<td><%= persona.id%></td>
        <td><%= persona.nombre1.capitalize+' '+persona.nombre2.capitalize+' '+persona.apellido1.capitalize+' '+persona.apellido2.capitalize%></td>
        <td><%= persona.cedula %></td>
        <td><%= persona.telefono1 %></td>
        <td >

                <%= link_to persona do %>
                   <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>

                 <%= link_to edit_persona_path(persona)   do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>

                 <%= link_to  persona, method: :delete, data: { confirm: 'Are you sure?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                <% end -%>
       </td>


      </tr>
    <% end %>



	</tbody>
	<tfoot>
		<tr>
			<th>Id</th>
			<th>Nombres y Apellidos</th>
			<th>Cedula</th>
			<th>Telefono</th>
			<th>Opciones</th>
		</tr>
	</tfoot>
</table>
<% else %>
  <p> no hay persona(s) con este criterio de busqueda: <%= params[:search] %>.</p>

<% end -%>



<%= paginate @personas %>


</div>

app/views/personas/new.html.erb
                <div id="page-title">

<h3>
    Nueva Persona
    <small>
         se agregan los datos de las personas y solicitudes.      <b>   Los campos con (*) son obligatorios</b>
    </small>
</h3>

</div><!-- #page-title -->

<%= render 'form' %>
<br/>
<%= link_to 'Volver', personas_path %>

app/views/personas/reporte_municipio_listado.html.erb
 <div align="right"><em>Reporte generado por la Coord. de Informatica y Sistemas el <%=Time.now.strftime("%d/%m/%Y a las %I:%M")%></em></div>
<b>Municipio: <%=@listado.last.municipio%> - Sector:  <%=@listado.last.sector%> </b><br />
<b>Fecha: <%=@listado.last.fecha.strftime("%d/%m/%Y")%></b>
<br /><br />

<table class="table-striped table-hover table-bordered table-condensed">
		<tr >
		<th>#No</th>
		<th>CEDULA</th>
		<th>NOMBRE Y APELLIDOS</th>
		<th>DIRECCION</th>
		<th>TELEFONO</th>
		<th>AYUDA (ESTADO)</th>

	</tr>
	<% if !@listado.blank?  %>

	<% @listado.each_with_index do |item, index|%>
		    	<tr>
		    				<th><%= index+1 %></th>
  							<th><%=item.cedula %></th>
							<th><%=item.nombres.capitalize%></th>
							<th><%=item.direccion.capitalize%></th>
							<th><%=item.telefono1%></th>
							<th>
							<% if !@listado_ayudas.blank? %>
							  <% for ayudas in @listado_ayudas %>
							   <% if ayudas.persona_id == item.id%>
							  	  	<li><%=ayudas.nombre%>	(<%=ayudas.estado%>)</li>
									<% end -%>

							  <% end %>
							<% end %>
							</th>
				</tr>
		  <% end %>
	<% end %>
</table>

app/views/personas/show.html.erb
<br/>
<%= notice %>
<h4 class="heading-1 clearfix">
    <i class="glyph-icon icon-tags heading-icon"></i>
    <div class="heading-content">
       <%=  @persona.nombre1.capitalize+' '+@persona.nombre2.capitalize+' '+@persona.apellido1.capitalize+' '+@persona.apellido2.capitalize%>.
        <small>
        <strong>Cedula de Identidad:</strong> <%= @persona.cedula %><br />
        <strong>Direccion: </strong><%= @persona.direccion.capitalize %>,  <%#= @persona.referencia.capitalize %>.<br />
        <strong>Telefonos :</strong><%= @persona.telefono1 %>   <%= @persona.telefono2 %>



        </small>
    </div>
</h4>


<div class="divider"></div>
<h4 class="heading-1 clearfix">
Familiares
<small>
<% if !@persona.families.blank?%>
      <% for item in @persona.families %>
        <li>    <%= "<strong> - </strong>#{item.nombre.capitalize} #{item.apellido.capitalize}, #{item.parentesco}".html_safe if !item.nombre.blank? %></li>

    <% end %>
<% end -%>
</small>

<div class="divider"></div>
<h4 class="heading-1 clearfix">
Estudio Socioeconomico
<small><%= "<strong>Empresa donde trabaja ó Ocupacion: #{@persona.economy.empresa}</strong>".html_safe if !@persona.economy.empresa.blank?  %> 
<%="(#{@persona.economy.sector} )" if !@persona.economy.sector.blank? %>
<%="<strong>Ingreso Familiar: </strong> #{@persona.economy.ingreso_familiar}Bs".html_safe if  !@persona.economy.ingreso_familiar.blank? %><br />

<%= "<strong>Tipo de Vivienda: </strong> #{@persona.economy.tipo_casa}".html_safe  if !@persona.economy.tipo_casa.blank?%>
<%= "<strong>Condiciones:  </strong>#{@persona.economy.condiciones_de_vivienda}".html_safe  if !@persona.economy.condiciones_de_vivienda.blank? %>
<%= "<strong>Personas/Hab: </strong> #{ @persona.economy.persona_hab}".html_safe if !@persona.economy.persona_hab.blank?%><br />


<%= "<strong>Cantidade de Hijos: </strong> #{@persona.economy.cant_hijos}".html_safe if !@persona.economy.cant_hijos.blank? %>
<%= "<strong>Enceres Compartidos: </strong>#{@persona.economy.enceres_compartidos}".html_safe if !@persona.economy.enceres_compartidos.blank? %>
<%= "<strong>Adultos Mayores: </strong> #{@persona.economy.adultos_mayores}".html_safe if !@persona.economy.adultos_mayores.blank? %>
<br />
<%= "<strong>Personas Discapacitadas: </strong>#{@persona.economy.discapacitados}".html_safe if !@persona.economy.discapacitados.blank? %>
<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.enfermos}".html_safe if !@persona.economy.enfermos.blank? %>


</small>
</h4>


<div class="divider"></div>
<h4 class="heading-1 clearfix">
Descripcion de la visita

<small>

<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.descripcion}".html_safe if !@persona.economy.descripcion.blank? %>
<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.pobreza_extrema}".html_safe if !@persona.economy.pobreza_extrema.blank? %>

</small>
</h4>

<div class="divider"></div>

<h4 class="heading-1 clearfix">
Conclusión(es)
<small>

<% if !@persona.conclusions.blank? %>
  <% for item in @persona.conclusions %>

  <li> 
          <%= "<strong>Solicitud : </strong> #{Ayuda.where(:id => item.ayuda_id).pluck(:nombre).first}".html_safe if !item.ayuda_id.blank? %>
          <%= "<strong>Estado de la solicitud : </strong>#{item.estado}".html_safe if !item.estado.blank? %>
          <%= "<strong>Fecha de la solicitud : </strong>#{item.fecha}".html_safe if !item.fecha.blank? %>
  </li>
  <div class="divider"></div>

  <% end %>
  <% else %>
            <%= "<strong>ESTA PERSONA NO POSEE SOLICITUDES REGISTRADAS</strong>".html_safe %>

<% end %>



</small>
</h4>

<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Volver', personas_path %>
<br/>
<br/>
<%= link_to  new_persona_path,:class=> "btn medium bg-blue" do %>
                                      <span class="button-content text-transform-upr font-bold font-size-11">Nueva Persona</span>
<% end -%>